allow_debugging: on
package_assets: on

javascripts:
  app:
    - public/javascripts/*.js
    - public/javascripts/**/*.js

stylesheets:
  app:
    - public/stylesheets/960.css
    - public/stylesheets/boilerplate.css
    - public/stylesheets/app.css
    - public/stylesheets/fonts.css
    - public/stylesheets/jquery.ui.stars.css
  login:
    - public/stylesheets/login/*.css
  ie: 
    - public/stylesheets/ie/*.css
 
