allow_debugging: on
package_assets: always
compress_assets: on
gzip_assets: on
javascript_comperssor: yui

javascripts:
  app:
    - public/javascripts/jquery-1.6.2.min.js
    - public/javascripts/jquery-ui-1.8.16.custom.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/bootstrap-modal.js
    - public/javascripts/underscore-min.js
    - public/javascripts/jquery.dump.js
    - public/javascripts/jquery.elastic.js
    - public/javascripts/jquery.autosuggest.js
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/jquery.jeditable.autogrow.js
    - public/javascripts/jquery.uploadify.v2.1.4.min.js
    - public/javascripts/jquery.remotipart.js
    - public/javascripts/jquery.timeago.js
    - public/javascripts/jquery.tipsy.js
    - public/javascripts/jquery.masonry.js
    - public/javascripts/jquery.watermark.min.js
    - public/javascripts/jquery.tablesorter.min.js
    - public/javascripts/jquery.class.js
    - public/javascripts/jquery.qtip.js
    - public/javascripts/swfobject.js
    - public/javascripts/twilio.min.js
    - public/javascripts/facebox.js
    - public/javascripts/ratings/*.js
    - public/javascripts/galleriffic/*.js
    - public/javascripts/cases.js
    - public/javascripts/application/comments.js
    - public/javascripts/prizzm.js
    - public/javascripts/application.js
    
  wysiwyg:
    - public/javascripts/jwysiwyg/jquery.wysiwyg.js
    - public/javascripts/jwysiwyg/controls/wysiwyg.link.js
    - public/javascripts/jwysiwyg/controls/wysiwyg.image.js
  item_detail:
    - public/javascripts/application/item_detail.js
 

stylesheets:
  app:
    - public/stylesheets/global.css
    - public/stylesheets/fonts.css
    - public/stylesheets/jquery.ui.stars.css
    - public/stylesheets/jquery.ui.autocomplete.css
    - public/stylesheets/jquery.ui.theme.css
    - public/stylesheets/facebox.css
    - public/stylesheets/galleriffic-3.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/ckeditor.css
    - public/stylesheets/tipsy.css
    - public/stylesheets/vendor/jquery.qtip.css
    - public/stylesheets/wizard.css

  wysiwyg:
    - public/stylesheets/jquery.wysiwyg.css

  logged_in:
    - public/stylesheets/application.css
  public:
    - public/stylesheets/application.css
  item_public:
    - public/stylesheets/item-public.css
  item_detail:
    - public/stylesheets/item-detail.css
  item_new:
    - public/stylesheets/item-new.css
  search_results:
    - public/stylesheets/search-results.css
  login:
    - public/stylesheets/login/*.css
  ie: 
    - public/stylesheets/ie/*.css
  profile:
    - public/stylesheets/profile.css
  profile_fix:
    - public/stylesheets/profile-public-fix.css
  case_detail:
    - public/stylesheets/case-detail.css
  company:
    - public/stylesheets/company.css
  welcome:
    - public/stylesheets/welcome.css
  people:
    - public/stylesheets/people.css
  yourstuff:
    - public/stylesheets/yourstuff.css
  landing:
    - public/stylesheets/global.css
    - public/stylesheets/fonts.css
    - public/stylesheets/landing.css
    - public/stylesheets/facebox.css
  corporate:
    - public/stylesheets/bootstrap.min.css
    - public/stylesheets/facebox.css
