allow_debugging: on
package_assets: always
compress_assets: on
gzip_assets: on

javascripts:
  app:
    - public/javascripts/rails.js
    - public/javascripts/underscore-min.js
    - public/javascripts/jquery.dump.js
    - public/javascripts/jquery.autogrow.js
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/jquery.jeditable.autogrow.js
    - public/javascripts/jquery.uploadify.v2.1.4.min.js
    - public/javascripts/jquery.nivo.slider.js
    - public/javascripts/jquery.timeago.js
    - public/javascripts/jquery.watermark.min.js
    - public/javascripts/swfobject.js
    - public/javascripts/facebox.js
    - public/javascripts/ratings/*.js
    - public/javascripts/galleriffic/*.js
    - public/javascripts/application.js

stylesheets:
  app:
    - public/stylesheets/960.css
    - public/stylesheets/boilerplate.css
    - public/stylesheets/main.css
    - public/stylesheets/fonts.css
    - public/stylesheets/jquery.ui.stars.css
    - public/stylesheets/nivo-slider.css
    - public/stylesheets/facebox.css
  items-page:
    - public/stylesheets/item-public.css
    - public/stylesheets/galleriffic-3.css
  login:
    - public/stylesheets/login/*.css
  ie: 
    - public/stylesheets/ie/*.css
