allow_debugging: on
package_assets: on
compress_assets: on
gzip_assets: on

javascripts:
  app:
    - public/javascripts/jquery-1.6.2.min.js
    - public/javascripts/jquery-ui-1.8.16.custom.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/underscore-min.js
    - public/javascripts/jquery.dump.js
    - public/javascripts/jquery.autogrow.js
    - public/javascripts/jquery.autosuggest.js
    - public/javascripts/jquery.form.js
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/jquery.jeditable.autogrow.js
    - public/javascripts/jquery.uploadify.v2.1.4.min.js
    - public/javascripts/jquery.nivo.slider.js
    - public/javascripts/jquery.remotipart.js
    - public/javascripts/jquery.timeago.js
    - public/javascripts/jquery.watermark.min.js
    - public/javascripts/swfobject.js
    - public/javascripts/twilio.min.js
    - public/javascripts/facebox.js
    - public/javascripts/ratings/*.js
    - public/javascripts/galleriffic/*.js
    - public/javascripts/application.js
    - public/javascripts/cases.js
    - public/javascripts/application/comments.js
    - public/javascripts/livefeed.js

stylesheets:
  app:
    - public/stylesheets/global.css
    - public/stylesheets/fonts.css
    - public/stylesheets/jquery.ui.stars.css
    - public/stylesheets/jquery.ui.autocomplete.css
    - public/stylesheets/jquery.ui.theme.css
    - public/stylesheets/nivo-slider.css
    - public/stylesheets/facebox.css
    - public/stylesheets/galleriffic-3.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/ckeditor.css

  logged_in:
    - public/stylesheets/application-logged-in.css
  public:
    - public/stylesheets/application-public.css

  item_public:
    - public/stylesheets/item-public.css
  item_detail:
    - public/stylesheets/item-detail.css
  item_new:
    - public/stylesheets/item-new.css
  search_results:
    - public/stylesheets/search-results.css
  login:
    - public/stylesheets/login/*.css
  ie: 
    - public/stylesheets/ie/*.css
  profile:
    - public/stylesheets/profile.css
  profile_fix:
    - public/stylesheets/profile-public-fix.css
  livef:
    - public/stylesheets/livef.css
  case_detail:
    - public/stylesheets/case-detail.css
  company:
    - public/stylesheets/company.css
